"""MangoHud frametime pipeline: config, launch options, live tail, epoch sync.

Verified facts on THIS install (MangoHud 0.8.4-1.1, 2026-10):

* The CSV log is written **live** while the app runs (the file grows each
  second), and the file's nanosecond **birth time** (statx stx_btime) equals
  the instant MangoHud starts logging.  That gives us the epoch anchor.

* CSV layout (no `log_versioning`):
      line 1: os,cpu,gpu,ram,kernel,driver,cpuscheduler        (metadata names)
      line 2: <values>
      line 3: fps,frametime,cpu_load,...,process_rss,cpu_mhz,elapsed
      line 4+: one row per frame

  `frametime` is milliseconds; `elapsed` is a monotonic clock in **nanoseconds**
  since logging started.

Epoch mapping (see docs/DETECTOR-COLLECT.md for validation):

      t_epoch(frame) = t0 + elapsed_ns / 1e9 + offset_s

  where `t0` is the MangoHud log file birth time and `offset_s` is a small
  calibration constant (default 0) measured with a SIGSTOP marker.  Accuracy
  target <= 50 ms; measured residual on this machine is reported by
  `tools/validate_mangohud_sync.py`.

Launch options: MangoHud can be enabled either via its `mangohud` LD_PRELOAD
wrapper, or -- for Dota's **native Vulkan** build -- purely through its Vulkan
implicit layer (`MANGOHUD=1`, layer `VK_LAYER_MANGOHUD_overlay_x86_64`), which
avoids adding an LD_PRELOAD (relevant because the history triage found
`LD_PRELOAD=""` helped).  Both are emitted by `launch_options()`.
"""

from __future__ import annotations

import math
import os
import threading
import time
from typing import Iterator, List, Optional, Tuple

from . import util
from .rundir import CsvWriter

MANGOHUD_SUBDIR = "mangohud"

# MangoHud occasionally emits a corrupt frame (fps ~1e-5, frametime ~1e8 ms).
# Anything above this is physically implausible and must not reach frametimes.csv
# (analysis-side mirror: detector/analyze/config.MAX_PLAUSIBLE_FRAMETIME_MS).
MAX_PLAUSIBLE_FRAMETIME_MS = 10_000.0


def plausible_frametime(ft: float) -> bool:
    """True if a per-frame frametime (ms) is finite, positive and plausible."""
    return math.isfinite(ft) and 0.0 < ft <= MAX_PLAUSIBLE_FRAMETIME_MS


def raw_dir(run_dir: str) -> str:
    return os.path.join(run_dir, "raw", MANGOHUD_SUBDIR)


def default_config(output_folder: str, extra: Optional[dict] = None) -> dict:
    """Config that yields per-frame `frametime` + `elapsed` columns."""
    cfg = {
        "output_folder": output_folder,
        "output_file": "",          # let MangoHud pick <app>_<date>.csv
        "autostart_log": "1",
        "log_duration": "0",        # 0 = unlimited; keep logging for the whole run
        "log_interval": "0",
        "fps_only": "0",            # must be 0 to keep the frametime column
    }
    if extra:
        cfg.update(extra)
    return cfg


def format_config(cfg: dict) -> str:
    """MangoHud config file body (KEY=VALUE lines, ';' comments)."""
    lines = ["# generated by `stutter collect`; do not edit while a run is active"]
    for k, v in cfg.items():
        lines.append(f"{k}={v}")
    return "\n".join(lines) + "\n"


def write_config_file(path: str, cfg: dict) -> str:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(format_config(cfg))
    return path


def config_env(cfg: dict) -> str:
    """Compact MANGOHUD_CONFIG value (no spaces, for inline env assignment)."""
    return ",".join(f"{k}={v}" for k, v in cfg.items())


def launch_options(conf_path: str, *, native_vulkan: bool = True,
                   keep_ld_preload_empty: bool = True) -> dict:
    """Return ready-to-paste Steam launch-option strings.

    Steam supports `VAR=value %command%`, so environment-only activation works.
    """
    extra_app = " -vulkan" if native_vulkan else ""
    layer = (f"MANGOHUD=1 MANGOHUD_CONFIGFILE={conf_path} "
             f"ENABLE_VKBASALT=0 %command%{extra_app}")
    if keep_ld_preload_empty:
        layer = f"LD_PRELOAD=\"\" {layer}"
    preload = f"MANGOHUD_CONFIGFILE={conf_path} mangohud %command%{extra_app}"
    return {
        # Preferred for the native Vulkan build: no LD_PRELOAD re-introduced.
        "native_vulkan_layer": layer,
        # Works for both native and Proton; uses the MangoHud LD_PRELOAD wrapper.
        "wrapper": preload,
        # Proton variant (same wrapper; Proton loads the layer in the wine process)
        "proton": f"MANGOHUD_CONFIGFILE={conf_path} mangohud %command%",
        "env_only": f"MANGOHUD=1 MANGOHUD_CONFIGFILE={conf_path}",
    }


# ---------------------------------------------------------------------------
# parsing
# ---------------------------------------------------------------------------

def parse_header(line: str) -> List[str]:
    return [c.strip() for c in line.rstrip("\n").split(",")]


def find_header_and_cols(path: str) -> Tuple[int, dict]:
    """Locate the data header line and return (line_index, {col: idx})."""
    with open(path, "r", errors="replace") as fh:
        for i, line in enumerate(fh):
            if line.startswith("fps,") and "frametime" in line:
                cols = parse_header(line)
                return i, {c: j for j, c in enumerate(cols)}
    raise ValueError(f"no MangoHud data header in {path}")


def iter_frames_from(path: str, start_offset: int, header_idx: int, cols: dict
                     ) -> Iterator[Tuple[int, float]]:
    """Yield (byte_offset_next, (elapsed_ns, frametime_ms)) for complete lines.

    Partial trailing lines are not consumed (start_offset is not advanced past
    them), so this is safe to call repeatedly on a growing file.
    """
    with open(path, "r", errors="replace") as fh:
        fh.seek(start_offset)
        pos = start_offset
        for line in fh:
            if not line.endswith("\n"):
                break
            pos += len(line.encode("utf-8", "replace"))
            if not line.strip():
                continue
            parts = line.rstrip("\n").split(",")
            try:
                ft = float(parts[cols["frametime"]])
                el = float(parts[cols["elapsed"]])
            except (KeyError, IndexError, ValueError):
                continue
            yield pos, (int(el), ft)


def read_frames(path: str) -> List[Tuple[int, float]]:
    """Parse a complete MangoHud CSV into [(elapsed_ns, frametime_ms)]."""
    idx, cols = find_header_and_cols(path)
    out = []
    for _pos, fr in iter_frames_from(path, 0, idx, cols):
        out.append(fr)
    return out


def _has_mh_header(path: str) -> bool:
    try:
        with open(path, "r", errors="replace") as fh:
            for _ in range(12):
                line = fh.readline()
                if not line:
                    return False
                if line.startswith("fps,") and "frametime" in line:
                    return True
    except OSError:
        return False
    return False


def find_log_file(folder: str, since_ns: Optional[int] = None,
                  reject: Optional[set] = None) -> Optional[str]:
    """Newest non-summary MangoHud CSV in *folder*.

    Only files that actually carry the MangoHud `fps,...,frametime,...` header
    are returned, so an unrelated CSV (e.g. our own frametimes.csv) is never
    mistaken for the upstream log.
    """
    best = None
    best_m = -1
    rejected = reject or set()
    try:
        names = os.listdir(folder)
    except OSError:
        return None
    for name in names:
        if not name.endswith(".csv") or name.endswith("_summary.csv"):
            continue
        p = os.path.join(folder, name)
        if p in rejected:
            continue
        try:
            m = os.path.getmtime(p)
            b = util.birthtime_ns(p)
        except OSError:
            continue
        ref = b if b is not None else int(m * 1e9)
        if since_ns is not None and ref < since_ns - 5_000_000_000:
            continue
        if m > best_m and _has_mh_header(p):
            best_m, best = m, p
    return best


# ---------------------------------------------------------------------------
# live watcher thread
# ---------------------------------------------------------------------------

class MangoHudWatcher:
    """Follow the MangoHud CSV in `folder` and write frametimes.csv on one clock."""

    def __init__(self, folder: str, writer: CsvWriter, offset_s: float = 0.0,
                 poll: float = 0.25, timeout: float = 600.0):
        self.folder = folder
        self.writer = writer
        self.offset_s = offset_s
        self.poll = poll
        self.timeout = timeout
        self.log_file: Optional[str] = None
        self.t0_epoch: Optional[float] = None
        self.birth_ns: Optional[int] = None
        self.n_frames = 0
        self.n_rejected = 0
        self._offset = 0
        self._header_idx = None
        self._cols = None
        self._rejected = set()
        self._stop = threading.Event()
        self._thread = None
        self.started_epoch = util.epoch()

    def start(self) -> None:
        self._thread = threading.Thread(target=self._run, name="mangohud", daemon=True)
        self._thread.start()

    def _run(self) -> None:
        deadline = time.monotonic() + self.timeout
        since_ns = util.epoch_ns()
        while not self._stop.is_set() and time.monotonic() < deadline:
            if self.log_file is None:
                p = find_log_file(self.folder, since_ns=since_ns, reject=self._rejected)
                if p:
                    self.log_file = p
                    bt = util.birthtime_ns(p)
                    self.birth_ns = bt
                    if bt is not None:
                        self.t0_epoch = bt / 1e9 + self.offset_s
                    else:
                        self.t0_epoch = os.path.getmtime(p) + self.offset_s
                    try:
                        self._header_idx, self._cols = find_header_and_cols(p)
                        with open(p, "r", errors="replace") as fh:
                            for _ in range(self._header_idx + 1):
                                fh.readline()
                            self._offset = fh.tell()
                    except (OSError, ValueError):
                        # not a usable MangoHud CSV; reject and keep looking
                        self._rejected.add(p)
                        self.log_file = None
                        self._header_idx = self._cols = None
            if self.log_file is not None and self._cols is not None:
                self._drain()
            self._stop.wait(self.poll)

    def _drain(self) -> None:
        assert self.log_file is not None
        new_offset = self._offset
        try:
            with open(self.log_file, "r", errors="replace") as fh:
                fh.seek(self._offset)
                for line in fh:
                    if not line.endswith("\n"):
                        break
                    new_offset += len(line.encode("utf-8", "replace"))
                    parts = line.rstrip("\n").split(",")
                    try:
                        ft = float(parts[self._cols["frametime"]])
                        el = int(float(parts[self._cols["elapsed"]]))
                    except (KeyError, IndexError, ValueError):
                        continue
                    if not plausible_frametime(ft):
                        self.n_rejected += 1
                        continue
                    t = (self.t0_epoch or 0.0) + el / 1e9
                    self.writer.write(t, [ft])
                    self.n_frames += 1
        except OSError:
            return
        self._offset = new_offset

    def flush(self) -> None:
        self._drain()

    def stop(self) -> None:
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=5)
            self._thread = None
        try:
            self._drain()
            self.writer.flush()
        except Exception:
            pass

    def info(self) -> dict:
        b = self.birth_ns
        return {
            "log_file": self.log_file,
            "birth_ns": b,
            "t0_epoch": self.t0_epoch,
            "offset_s": self.offset_s,
            "n_frames": self.n_frames,
            "n_rejected": self.n_rejected,
        }


def mapping_residuals(frames: List[Tuple[int, float]], t0: float,
                      markers: List[float]) -> List[float]:
    """Residual (ms) between each marker and the nearest mapped frame epoch.

    Used by tools/validate_mangohud_sync.py: for a SIGSTOP of known duration we
    expect the largest frametime spike's mapped epoch to land on the marker.
    """
    if not frames:
        return []
    times = [t0 + el / 1e9 for el, _ft in frames]
    out = []
    for mk in markers:
        nearest = min(times, key=lambda x: abs(x - mk))
        out.append((nearest - mk) * 1000.0)
    return out
